
# language: generic (this is if we get a 'rakefile not found' error")

# script:
#   - docker run -e CI=true USERNAME/react-test npm test
sudo: required
services:
  - docker

before_install:
  - docker build -t alexandertroup/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexandertroup/react-test npm test

after_success:
  - docker build -t alexandertroup/multi-client ./client
  - docker build -t alexandertroup/multi-nginx ./nginx
  - docker build -t alexandertroup/multi-server ./server
  - docker build -t alexandertroup/multi-worker ./worker
  
  # Log in to docker CLI
  - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push alexandertroup/multi-client
  - docker push alexandertroup/multi-nginx
  - docker push alexandertroup/multi-server
  - docker push alexandertroup/multi-worker
